server:
  port: ${bestball.port:9010}
  env: ${environment:dev}

spring:
  datasource:
    url: ${datasource.url:jdbc:h2:mem:testdb}
    driverClassName: ${datasource.driver:org.h2.Driver}
    username: ${datasource.username:sa}
    password: ${datasource.password:password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    database-platform: ${datasource.platform:org.hibernate.dialect.H2Dialect}

golf:
  pga:
    update:
      rate: ${pga.update.rate:5000}
