server:
  port: ${PORT:9010}
  env: ${environment:dev}

spring:
  datasource:
    url: ${datasource.url:jdbc:h2:mem:testdb}
    driverClassName: ${datasource.driver:org.h2.Driver}
    username: ${datasource.username:sa}
    password: ${datasource.password:}
    data: ${datasource.data:}
  jpa:
    show-sql: false
    database-platform: ${datasource.platform:org.hibernate.dialect.H2Dialect}

golf:
  pga:
    update:
      rate:
        rankings: ${pga.update.rate.rankings:60000}
        schedule: ${pga.update.rate.schedule:60000}
        tournament: ${pga.update.rate.tournament:60000}
  api:
    key: ${pga.api.key:f98dc8be2021416fad32beaa8a1929ec}
